version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: keepitup_postgres
    environment:
      POSTGRES_USER: fran
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: keepitup
    ports:
      - "5432:5432"
    networks:
      - keepitup-network
    volumes:  # Fix: properly indented under 'postgres' service
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fran"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot:
    build:
      context: ./KeepItUpBack
      dockerfile: Dockerfile
    container_name: springboot-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - keepitup-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/keepitup
      SPRING_DATASOURCE_USERNAME: fran
      SPRING_DATASOURCE_PASSWORD: 123
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: appkeepitup@gmail.com
      SMTP_PASS: "ezro bmsd wcpm mzka"

  angular:
    build:
      context: ./KeepItUpFront
      dockerfile: Dockerfile
    container_name: angular-container
    depends_on:
      springboot:
        condition: service_started
    ports:
      - "4200:4200"
    networks:
      - keepitup-network

networks:
  keepitup-network:
    driver: bridge

volumes:  # Define named volumes at the root level
  postgres-data:
