export const LOCATIONS = {
  landing: '/',
  login: '/login',
  register: '/register',
  menu: '/menu',
  weighins: '/weighins',
  workouts: '/workouts',
  plans: '/plans',
  logregistry: '/log-registry',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  settings: '/settings',
  gymManager: '/gym-manager'
};

export const MSG = {
  failedCredentials: 'MSG.FAILED_CREDENTIALS',
  unknownLoginError: 'MSG.UNKNOWN_LOGIN_ERROR',
  fetcherror: 'MSG.FETCH_ERROR',
  unauthorized: 'MSG.UNAUTHORIZED',
  notoken: 'MSG.NO_TOKEN',
  noauthtoken: 'MSG.NO_AUTH_TOKEN',
  loginerror: 'MSG.LOGIN_ERROR',
  errorcreatingworkout: 'MSG.ERROR_CREATING_WORKOUT',
  errorfetchcurrentuser: 'MSG.ERRORFETCHINGCURRENTUSER',
};

export const TOAST_MSGS = {
  login: 'TOAST_MSGS.LOGIN',
  logout: 'TOAST_MSGS.LOGOUT',
  register: 'TOAST_MSGS.REGISTER',
  errorregister: 'TOAST_MSGS.ERROR_REGISTER',
  alreadyexists: 'TOAST_MSGS.ALREADY_EXISTS',
  fillallfields: 'TOAST_MSGS.FILL_ALL_FIELDS',
  emailsent: 'TOAST_MSGS.EMAIL_SENT',
  editmodedisabled: 'TOAST_MSGS.EDIT_MODE_DISABLED',
  editmode: 'TOAST_MSGS.EDIT_MODE',
  workoutdeletedsaved: 'TOAST_MSGS.WORKOUT_DELETED_SAVED',
  noexercisesinworkout: 'TOAST_MSGS.NO_EXERCISES_IN_WORKOUT',
  exercisecreated: 'TOAST_MSGS.EXERCISE_CREATED',
  notessavedsuccessfully: 'TOAST_MSGS.NOTES_SAVED_SUCCESSFULLY',
  errorcreatingworkout: 'TOAST_MSGS.ERROR_CREATED',
  cantdeleteallsets: 'TOAST_MSGS.CANT_DELETE_ALL_SETS',
  failedtodeleteexercise: 'TOAST_MSGS.FAILED_TO_DELETE_EXERCISE',
  errorcreatingexercise: 'TOAST_MSGS.ERROR_CREATING_EXERCISE',
  exercisealreadyexists: 'TOAST_MSGS.EXERCISEALREADYEXISTS',
  failedtocreateexercise: 'TOAST_MSGS.FAILEDTOCREATEEXERCISE',
  reorderingsaved: 'TOAST_MSGS.REORDERING_SAVED',
  failedtosavereordering: 'TOAST_MSGS.FAILEDTOSAVEREORDERING',
  exercise_created: 'TOAST_MSGS.EXERCISECREATED_',
  pleasefillallfields:'TOAST_MSGS.PLEASE_FILL_ALL_FIELDS',
  exercise_deleted_successfully:'TOAST_MSGS.EXERCISE_DELETED_SUCCESSFULLY',
  failed_to_delete_exercise:'TOAST_MSGS.FAILED_TO_DELETE_EXERCISE',

  successfulresetpassword: 'TOAST_MSGS.SUCCESSFUL_RESETPASSWORD',
  failedreseting: 'TOAST_MSGS.FAILED_RESETING',
  successcheckyouremail: 'TOAST_MSGS.SUCCESS_CHECK_YOUR_EMAIL',
  failedresetlink: 'TOAST_MSGS.FAILED_RESET_LINK',
};

export const ASSET_URLS = {
  gmailicon: 'module_assets/landing-assets/gmailicon.png',
  linkedinicon: 'module_assets/landing-assets/linkedinicon.png',
  background: 'module_assets/landing-assets/background.mp4',
  spain: '/module_assets/translation-flags/spain.svg',
  english: '/module_assets/translation-flags/english.svg',
  sun: '/module_assets/landing-assets/sun.svg',
  moon: '/module_assets/landing-assets/moon.svg',
  ThreeDotsIcon: 'module_assets/plans-assets/ThreeDotsIcon.svg',
  PlusSignIcon: 'module_assets/plans-assets/PlusSignIcon.svg',
  DeleteIcon: 'module_assets/plans-assets/DeleteIcon.svg',
  PlayIcon: 'module_assets/plans-assets/PlayIcon.svg',
  NotesIcon: 'module_assets/plans-assets/NotesIcon.svg',
};
