# Use Node.js image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install Angular CLI globally to use ng serve
RUN npm install -g @angular/cli

# Copy all source files
COPY . .

# Expose the Angular development server port
EXPOSE 4200

# Start the Angular app in development mode
CMD ["npm", "run", "start"]
